# src/models/schemas.py
from pydantic import BaseModel, Field

class QueryRequest(BaseModel):
    """
    Validates incoming user query payloads.
    """
    question: str = Field(
        ..., 
        description="The natural language question to be executed against the indexed collection vector space.",
        examples=["What machine learning engineering experience does Kanz have?"]
    )

class QueryResponse(BaseModel):
    """
    Structures the outgoing synchronized inference response back to the client.
    """
    query: str = Field(..., description="The original incoming natural language query string.")
    answer: str = Field(..., description="The synthesized text answer generated by the context-bounded LLM matrix layer.")
    context_used: list[str] = Field(
        default=[], 
        description="The collection of high-density Parent text context blocks retrieved and applied during generation."
    )